version: '3'

services:
 
  db:
    image: mysql 
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_ROOT_PASSWORD=password12
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak 
 #   volumes_from:
    volumes:
      - db_accounts:/var/lib/mysql
 
  sso:
    build: sso 
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_DATABASE=keycloak
      - MYSQL_USERNAME=keycloak
      - MYSQL_PASSWORD=keycloak 
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
    ports:
      - "8080:8080"
    links:
      - db:mysql
    volumes:
      - db_accounts:/var/lib/mysql

   

  api:      
    image: dina/accounts-api:v0.1
#    build: ./api
    depends_on: 
      - sso
    ports:
      - "8181:8181"
    links:
      - sso
#    environment:
#      - VIRTUAL_HOST=api
#      - VIRTUAL_PORT=8181

  ui:
    image: dina/accounts-ui:v0.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.template
    environment:
      - VIRTUAL_HOST=beta-accounts.dina-web.net
      - VIRTUAL_PROTO=http
      - NGINX_HOST=beta-accounts.dina-web.net
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT $$NGINX_INDEX' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  

volumes:
  db_accounts: 
 