#!make

PWD=$(shell pwd)
include env/.envaccounts

all: init build dotfiles sso-init up
.PHONY: all

init:

sso-init:
	@test ! -f $(PWD)/env/.envaccounts || echo "Please run 'make dotfiles' first."
	# this adds a master user to KeyCloak using environment settings from env/.envaccounts
	docker-compose up -d sso
#	docker-compose run sso keycloak/bin/add-user-keycloak.sh -u $(ACCOUNTS_ROOT) -p $(ACCOUNTS_PASS)
	docker-compose run sso keycloak/bin/add-user-keycloak.sh -u admin -p dina
	docker-compose restart sso

build: build-api build-ui build-sso

build-sso:
	make -C sso

build-api:
	docker run -it --rm --name my-maven-project \
		-v $(PWD):/usr/src/mymaven \
		-v $(PWD)/m2:/root/.m2 \
		-w /usr/src/mymaven \
		maven:3 bash -c "mvn package"
	make -C accounts-api

build-ui:
	docker run -it --rm --name my-ember-project \
		-v $(PWD)/user-management-ui:/myapp \
		danlynn/ember-cli:2.11.1 \
      sh -c "npm install && bower --allow-root install && ember build" 
	make -C user-management-ui

secrets:
	#echo "# Make this unique, and don't share it with anybody.\n# This value was autogenerated." > $@
	#rm -f secrets env/{.envmysql}
	printf "export SECRET_MYSQL_ROOT_PASSWORD=%b\n" \
		$$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 50) >> $@
	printf "export SECRET_MYSQL_PASSWORD=%b\n" \
		$$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 50) >> $@

dotfiles: secrets
	# for mac only.  envsubst is not in mac
	bash -c ". secrets && eval < env/envmysql.template > env/.envmysql"
	bash -c ". secrets && eval < env/envaccounts.template > env/.envaccounts"

	#bash -c ". secrets && envsubst < env/envmysql.template > env/.envmysql"
	#bash -c ". secrets && envsubst < env/envaccounts.template > env/.envaccounts"

up:
	docker-compose up -d

down:
	docker-compose down

release:
	docker push dina/keycloak:v0.1
	docker push dina/accounts-api:v0.1
	docker push dina/accounts-ui:v0.1

